## Append samples of your project ##
resources:
- supervision_v1alpha1_costfunction.yaml
- supervision_v1alpha1_operatingpolicy.yaml
- supervision_v1alpha1_plant.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
